spring.application.name=support-chatbot

# PostgreSQL Production Configuration for Neon Tech Platform
spring.datasource.url=jdbc:postgresql://ep-misty-bird-aokygp5s-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
# HIDE DATABASE PASSWORD
spring.datasource.password=${NEON_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Tuning for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Hikari Connection Pool settings optimized for Neon Serverless database
spring.datasource.hikari.keepaliveTime=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.maximum-pool-size=8

# ==========================================
# FREE FOREVER AI CONFIGURATION (GROQ CLOUD)
# ==========================================
# HIDE GROQ API KEY
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai

# Setting our high-speed, free-tier open-source model
spring.ai.openai.chat.options.model=llama-3.1-8b-instant